services:
  frank:
    build:
      context: .
      args:
        FF_VERSION: ${FF_VERSION:-9.1.0}
    image: wearefrank/mijnzaaknotificaties:${VERSION:-latest}
    ports:
      - "${PORT:-8080}:8080"
    environment:
      application.server.type.custom: ${TRANSACTION_MANAGER:-NARAYANA}
      credentialFactory.class: nl.nn.credentialprovider.PropertyFileCredentialFactory
      credentialFactory.map.properties: /opt/frank/secrets/credentials.properties
      TZ: ${TIME_ZONE:-Europe/Amsterdam}
    env_file:
      - .env
    volumes:
      - ${SECRETS_PATH:-./src/main/secrets}:/opt/frank/secrets
      - ./src/main/resources/oauth-role-mapping.properties:/opt/frank/resources/oauth-role-mapping.properties
      - ${VOLUME_LOPENDEZAKEN_RESULTATEN:-lopendezaken-resultaten}:/MijnZaakNotificatiesFiles # Comment this out for local development
    restart: unless-stopped

